import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/providers/theme-provider";
import { ModeToggle } from "@/components/modeToggle";
const inter = Inter({ subsets: ["latin"] });
import {
  ClerkProvider, RedirectToSignIn, SignInButton, SignedIn, SignedOut, UserButton} from '@clerk/nextjs'
import Header from "@/components/Nav";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Header />
          {children}
          <SignedOut>
            <RedirectToSignIn redirectUrl='/sign-in' />
          </SignedOut>
          {/* <SignedIn>
            <UserButton />
          </SignedIn> */}
          {/* <ModeToggle /> */}
        </ThemeProvider>
      </body>
    </html>
  </ClerkProvider>
  );
}
